---
name: Sphinx Build on push and pull request
on:
  push:
    branches: [lint-branch]
  pull_request:
    branches: [master]
permissions: read-all
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install jsdoc
        run: npm install -g jsdoc

      - name: Install Sphinx
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "docs/"
